### ISSUE TITLE
Sample size calculation for minimum effect test

### ISSUE THREAD

**Issue by Schaubert** [Lakens/TOSTER#74]
Hello everyone, thanks for TOSTER, I have the feeling this is what I tried to teach (using confidence intervals) to my students the last years without knowing that the concept of minimum effect tests exists. I have a request on power/sample size calculation for minimum effect tests:

Couldn't power_t_TOST be altered in such a way that it provides a sample size calculation for a minimum effects test, in cases where the expected true mean difference is beyond the equivalence bounds? Currently, such a case gives the following error message: 

True mean difference greater than bounds. TOST power calculation not possible.

Currently, I find it hard to figure out how to do sample size calculation for a minimum effect test with TOSTER. I assume, what you have to do is to act as if you want to do an eqiuvalence test, with one of the equivalence bounds as the real one (the one closer to the true effect) and the other a value far away from (and on the other side of) the true effect. Is that true? Couldn't this then be done as a default whenever one tries to do sample size calculation for expected sample sizes beyond the equivalence bounds? It could come with a warning or some explanatory text.

**Comment by arcaldwell49** [comment]
Sorry for taking so long to get to this message. The error message is correct since this function is intended only for equivalence tests.

All you need for a MET is a one-tailed power analysis. Therefore, the base power.t.test or pwr's pwr_t_test will suffice for your needs. 

TOST for equivalence requires a specialized analysis because the test is that the CI are *between* to bounds (not outside them)
